variables:
    GIT_SUBMODULE_STRATEGY: recursive

image: debian:stable

before_script:
    - apt-get update
    - apt-get install -y make git
    - make build_dep

test:
    script:
        - make cover
