language: minimal

#
# Could add this to the cpanfile, but "normally" I dont need it, as I use
# the local Devel::Cover html report.
#
before_script:
    - sudo make build_dep

script:
    - make cover
    - cover -report codecov
