#!/usr/bin/env perl
use warnings;
use strict;
#
# Process the given files and output one big merged gpx
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");

use XML::Twig;
use IO::File;

use SplitList::Time;
use GPX::Files;

my $splitlist = SplitList::Time->new();
my $split_filename = shift @ARGV;
my $split_fh = IO::File->new($split_filename, "r");
$splitlist->parse_fd($split_fh);

my $gpxfiles = GPX::Files->new();
$gpxfiles->set_splitlist($splitlist);

for my $file (@ARGV) {
    printf("file: %s\n",$file);

    my $fh;
    if ( $file =~ m/\.gz$/ ) {
        $fh = IO::File->new("gzip -dc <'$file' |");
    } elsif ( $file =~ m/\.xz$/ ) {
        $fh = IO::File->new("xz -dc <'$file' |");
    } else {
        $fh = IO::File->new($file,"r");
    }
    if (!defined $fh) {
        die "could not open $file: $!";
    }

    my $twig = XML::Twig->new(
            start_tag_handlers => {
                trkseg => sub {$gpxfiles->add_trkseg()},
            },
            twig_handlers => {
                'trk/name' => sub {$gpxfiles->add_trk_name($_[1])},
                trkpt => sub {
                    $gpxfiles->add_trkpt($_[1]);
                    $_[1]->purge();
                },
            },
    );
    $twig->parse($fh);
}

$gpxfiles->flush();
