#!/usr/bin/env perl
use warnings;
use strict;
#
# Process the given files and output one big merged gpx
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");

use XML::Twig;
use GPX;

for my $file (@ARGV) {
    printf("file: %s\n",$file);
    my $gpx = GPX->new();
    $gpx->output_file(*STDOUT);
    my $twig = XML::Twig->new(
            start_tag_handlers => {
                trkseg => sub {$gpx->add_trkseg()},
            },
            twig_handlers => {
                'trk/name' => sub {$gpx->add_trk_name($_[1])},
                trkpt => sub {
                    $gpx->add_trkpt($_[1]);
                    $_[1]->purge();
                },
            },
    );
    $twig->parsefile($file);
    print($gpx->_flush());
}

